print (" Hi there ... ")
name=input("Enter the name of course :")
name2=input("Enter the second name of course (what u want to learn?) :")
p1= f"I’m a student from Egypt and want to learn {name}. I think it will be beneficial for this is work. But I’ve no job of my own to carry the expenses to pay for the certificate of this course. I live only for my scholarship ( $37 per month). In this circumstance, it is very much difficult for me to gather such amount of money for the certificate. Financial Aid will help me take this course without any adverse impact on my monthly essential needs. So I’m badly in need of this financial aid. I want to take this course as I want to learn {name2} in English. I want to complete the {name2}: Customer Needs and Wants Course on offer by {name2}. This course will boost my job prospects after graduation from my institute. It will help perform better in carrying out the order and give me an edge over my competitors. A verified certificate will attach credibility to the certificate I receive from this course. I plan to complete all assignments on or before time as I have done in previous Signature Track Courses. Also, I intend to participate in Discussion Forums, which I have found to supplement my learning immensely in the other online courses I have taken on Courser. Also, .plan to grade assignments which are to peer-reviewed which I believe will an invaluable learning opportunity."

p2=f"I can't pay for this course. I want to take this course as I want to complete the {name} on Coursera. I need financial aid because I am from Egypt and my income cannot pay for this course. Now I do not have a job to pay for it. My father income cannot either pay for it. I'm a student at faculty of computers and artificial intelligence, I didn't start my career yet and I need financial aid because I can't afford the courses without having a job. I need to take this course to work and have money to increase my skill and help my father. I plan to complete all assignments on or before times I have done in previous Signature Track Courses. Also, I intend to participate in Discussion Forums, which I have found to supplement my learning immensely in the other online courses I have taken on Coursera. I also plan to grade assignments which are to peer-reviewed which I believe will an invaluable learning opportunity. I hope these reasons are enough I thank you. So I need your help by giving me financial aid. The course will help me study {name2} that may helps me work freelance to earn money. I'll always participate in the discussion forums and help others with my knowledge. I will meet deadlines and will not hesitate to ask if there's something I don't understand the certificate would be a valuable thing for me because it'll help me get better job opportunities and start my career as fast as possible. It'll show that I'm a hard worker and self-learner also that I'm very active. I want to add to my CV in the future. Then I want to complete the {name} on Coursera. I think it will be beneficial for my thesis work. A verified certificate will attach credibility to the certificate I receive from this course. I will share my information to help others to learn and work to earn money. I hope that you. give me the chance. And finally, thank you."

print("First Question :")
print("  "*70)
print(p1)
print("  "*70)
print("***" * 60)
print("  "*70)
print("Second Question :")
print("  "*70)
print(p2)